defaultTheme: light
disableThemeToggle: true

profileMode:
  enabled: true
  title: "Maria Chietera"
  subtitle: "Agile & NeuroMindfulness Coach"
  imageUrl: "https://avatars.githubusercontent.com/u/2708146?v=4"
  imageTitle: "Profile Picture"
  imageWidth: 120
  imageHeight: 120
  buttons:
    - name: Posts
      url: "/posts"

socialIcons:
  - name: "twitter"
    url: "https://twitter.com/mchietera"
  - name: "linkedin"
    url: "https://www.linkedin.com/in/mariachietera/"