defaultTheme: light
disableThemeToggle: true

profileMode:
  enabled: true
  title: "Maria Chietera"
  subtitle: "Mindfulness & Coaching"
  imageUrl: "https://avatars.githubusercontent.com/u/2708146?v=4"
  imageTitle: "Profile Picture"
  imageWidth: 120
  imageHeight: 120
  buttons:
    - name: About
      url: "/about"
    - name: Book a discovery call
      url: "https://calendly.com/mariachietera/30min"
    - name: Subscribe to my newsletter
      url: "https://linktr.ee/mariachietera?lt_utm_source=lt_share_link#249377355"
    

socialIcons:
  - name: "linkedin"
    url: "https://www.linkedin.com/in/mariachietera/"
  - name: "instagram"
    url: "https://instagram.com/maria.chietera.coach/"